spring:
  mail:
    host: smtp.mail.ru
    port: 25
    username: newbookstest@mail.ru
    password: planeta11
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: "*"
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost/checklib
    username: postgres
    password: qqq
    initialization-mode: never
    connectionProperties:
      useUnicode: true
      characterEncoding: utf-8

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: false


server:
  port: ${PORT:8090}

logging:
  file: my.log

jwt:
  sessionTime: 1200000000
  secret: SecretKeyToGenJWTs

app:
  server-email:  newbookstest@mail.ru
  itemsPerPage: 4

management:
  endpoint:
    health:
      show-details: always

